"""update supports table

Revision ID: 053afded2b51
Revises: 8de374df7a93
Create Date: 2025-01-31 03:13:44.463781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053afded2b51'
down_revision: Union[str, None] = '8de374df7a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buildings_university_id_fkey', 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'university_id')
    op.alter_column('supports', 'sub_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'supports', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supports', type_='unique')
    op.alter_column('supports', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supports', 'sub_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('buildings', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('buildings_university_id_fkey', 'buildings', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###
