"""건물 추가정보 nullable 속성 추가

Revision ID: 3a81aab7cb36
Revises: 61965c1ffcec
Create Date: 2025-02-03 02:18:09.600104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a81aab7cb36'
down_revision: Union[str, None] = '61965c1ffcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'place',
               existing_type=postgresql.ENUM('구내', '구외', name='placeenum'),
               nullable=True)
    op.alter_column('buildings', 'structure',
               existing_type=postgresql.ENUM('ST', '경량ST', 'SRC', 'RC', '석조', '벽돌조', name='structenum'),
               nullable=True)
    op.alter_column('buildings', 'floor_under',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'floor_above',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'completion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('buildings', 'building_area',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'total_floor_area',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'year_elapsed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buildings', 'safety',
               existing_type=postgresql.ENUM('A', 'B', 'C', name='safetyenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'safety',
               existing_type=postgresql.ENUM('A', 'B', 'C', name='safetyenum'),
               nullable=False)
    op.alter_column('buildings', 'year_elapsed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'total_floor_area',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'building_area',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'completion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('buildings', 'floor_above',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'floor_under',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buildings', 'structure',
               existing_type=postgresql.ENUM('ST', '경량ST', 'SRC', 'RC', '석조', '벽돌조', name='structenum'),
               nullable=False)
    op.alter_column('buildings', 'place',
               existing_type=postgresql.ENUM('구내', '구외', name='placeenum'),
               nullable=False)
    # ### end Alembic commands ###
