"""update professor tables

Revision ID: 413b6db18ad9
Revises: 9ded957204fe
Create Date: 2025-01-20 23:35:00.218867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413b6db18ad9'
down_revision: Union[str, None] = '9ded957204fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professor_detail_chunks_professor_id_fkey', 'professor_detail_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'professor_detail_chunks', 'professors', ['professor_id'], ['id'], ondelete='CASCADE')
    op.add_column('professors', sa.Column('url', sa.String(), nullable=False))
    op.drop_constraint('uq_department_seq', 'professors', type_='unique')
    op.create_unique_constraint(None, 'professors', ['url'])
    op.drop_column('professors', 'seq')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'professors', type_='unique')
    op.create_unique_constraint('uq_department_seq', 'professors', ['seq', 'department_id'])
    op.drop_column('professors', 'url')
    op.drop_constraint(None, 'professor_detail_chunks', type_='foreignkey')
    op.create_foreign_key('professor_detail_chunks_professor_id_fkey', 'professor_detail_chunks', 'professors', ['professor_id'], ['id'])
    # ### end Alembic commands ###
