"""학사일정 학기 구분 nullable

Revision ID: 52432bfbaee2
Revises: 114938ffb3f4
Create Date: 2025-02-02 03:16:08.026155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52432bfbaee2'
down_revision: Union[str, None] = '114938ffb3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
