"""건물-빌딩 관계 업데이트

Revision ID: 61965c1ffcec
Revises: db802a4ee9d9
Create Date: 2025-02-03 02:10:11.586659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61965c1ffcec'
down_revision: Union[str, None] = 'db802a4ee9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_building_association_building_num_fkey', 'department_building_association', type_='foreignkey')
    op.create_foreign_key(None, 'department_building_association', 'buildings', ['building_num'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department_building_association', type_='foreignkey')
    op.create_foreign_key('department_building_association_building_num_fkey', 'department_building_association', 'buildings', ['building_num'], ['building_num'])
    # ### end Alembic commands ###
