"""공지사항에 학기 구분 추가

Revision ID: a321a294d193
Revises: 697d4c9be412
Create Date: 2025-02-02 04:15:07.151262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a321a294d193'
down_revision: Union[str, None] = '697d4c9be412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('semester_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notices', 'semesters', ['semester_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_column('notices', 'semester_id')
    # ### end Alembic commands ###
