"""main_department 삭제

Revision ID: afe8a1d6d543
Revises: 2d91f0e03946
Create Date: 2025-02-03 02:33:48.831000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe8a1d6d543'
down_revision: Union[str, None] = '2d91f0e03946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'main_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('main_department', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
