"""건물-학과 관계 업데이트

Revision ID: b2e0324c6b7c
Revises: a321a294d193
Create Date: 2025-02-03 01:49:40.112646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e0324c6b7c'
down_revision: Union[str, None] = 'a321a294d193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buildings_department_id_fkey', 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('buildings_department_id_fkey', 'buildings', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
